# Generated by Django 5.1.4 on 2025-03-26 16:40

import Connectly.models
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Connectly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_file',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, validators=[Connectly.models.validate_media_file], verbose_name='media_file'),
        ),
    ]
