# Generated by Django 5.1.4 on 2025-03-26 19:59

import Connectly.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connectly', '0003_alter_post_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_file',
            field=models.FileField(null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=Connectly.models.upload_location, validators=[Connectly.models.validate_media_file]),
        ),
    ]
