# Generated by Django 5.1.4 on 2025-03-26 20:51

import Connectly.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connectly', '0007_alter_post_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=Connectly.models.upload_location),
        ),
    ]
