# Generated by Django 5.1.4 on 2025-01-18 14:38

import Connectly.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connectly', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_file',
            field=models.FileField(null=True, upload_to=Connectly.models.upload_location, validators=[Connectly.models.validate_media_file]),
        ),
    ]
