# Generated by Django 5.1.4 on 2025-02-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connectly', '0003_post_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='Connectly.profile'),
        ),
    ]
