# Generated by Django 5.1.4 on 2025-02-04 13:21

import Connectly.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connectly', '0005_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=Connectly.models.upload_location),
        ),
    ]
