# Generated by Django 5.1.4 on 2025-02-08 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Connectly', '0006_profile_bio_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
