# Generated by Django 5.1.4 on 2025-03-09 21:05

import Connectly.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connectly', '0014_profileedit_remove_groupmessages_group_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileEdit',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=Connectly.models.upload_location),
        ),
    ]
