# Generated by Django 5.1.4 on 2025-03-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Connectly', '0015_delete_profileedit_profile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated',
        ),
    ]
