# Generated by Django 5.1.4 on 2025-03-22 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Connectly', '0011_remove_post_updated_alter_post_author'),
        ('Connectly', '0017_comment'),
    ]

    operations = [
    ]
